### ISSUE TITLE
No graph for CPU and Memory in Docker Container

### ISSUE THREAD

**Issue by Maxwell2022** [FormidableLabs/nodejs-dashboard#10]
Not sure this can be fixed or not

![screen shot 2016-10-13 at 11 21 17 am](https://cloud.githubusercontent.com/assets/670701/19332392/4781fac2-9137-11e6-80a9-020bc5dcf951.png)

**Comment by jasonwilson** [comment]
Can you describe the setup a little more? Is the dashboard and agent running in the container?

**Comment by comradealain** [comment]
I am also facing this issue. Although I am running dashboard on my local machine.

**Comment by daithi-coombes** [comment]
Mine is same as above. Seems its not polling or can't connect to socketio? 0% memory and no cpu - logs are working as expected.

`"nodejs-dashboard": "^0.1.0"`

```bash
$ cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
...
$ uname -a
Linux daithi-laptop 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
```

**Comment by daithi-coombes** [comment]
also tests are failing for nodejs-dashboard
```
$ mocha --recursive test/**/*.js
  dashboard-agent
    initialization
      ✓ should use environment variables for configuration (134ms)
    reporting
Reporting from a test app, 1.
Reporting from a test app, 2.
      1) should provide basic metrics
Slow call started...
Completed in:  318
Reporting from a test app, 3.
      ✓ should report an event loop delay (1011ms)

  2 passing (3s)
  1 failing

  1) dashboard-agent reporting should provide basic metrics:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

Note: not using a docker container

**Comment by daithi-coombes** [comment]
@Maxwell2022 @comradealain Seems the agent wasn't running so no metric events were emitted. I've created a `PR` with a quickfix that solves the issue for me: https://github.com/FormidableLabs/nodejs-dashboard/pull/20

**Comment by jasonwilson** [comment]
@Maxwell2022 did you `require("nodejs-dashboard");` from within your app? I was able to successfully run within a docker container using slightly modified version of @enko's gist https://gist.github.com/enko/31be945ca47b0c481275e76a2b695714

Replaced the test code with:
```
require("nodejs-dashboard");

setInterval(() => {
  console.log("hello from docker");
}, 1000);
```
<img width="1119" alt="screen shot 2016-10-13 at 8 12 54 pm" src="https://cloud.githubusercontent.com/assets/1151656/19374595/dac4d90e-9181-11e6-95bd-cd7d344f0fc6.png">

**Comment by jjasonclark** [comment]
This issue could be related to https://github.com/FormidableLabs/nodejs-dashboard/issues/15

**Comment by ryan-roemer** [comment]
@Maxwell2022 -- Can you update to latest nodejs-dashboard, check out #15 for possibly solutions and report back if the issue persists?

If it does, please create a minimal repository that exposes the issue with install + error reproduction steps and we'll jump in and figure things out. Thanks!

**Comment by jjasonclark** [comment]
PR https://github.com/FormidableLabs/nodejs-dashboard/pull/74 has been merged with more setup instructions for Docker and Docker compose based on what was found in this issue.

**Comment by jjasonclark** [comment]
Closing, both issues (display and execution) have been solved via merged PRs.
