### ISSUE TITLE
Stdout and stderr not updating

### ISSUE THREAD

**Issue by comradealain** [FormidableLabs/nodejs-dashboard#14]
I am consoling to stdout and stderr but dashboard updates with none of them. My index.js code is as follows:

```
require('nodejs-dashboard')
const http = require('http')  
const port = 4000

const requestHandler = (request, response) => {  
  console.log('Printing on stdout: ',request.url)
console.error('Printing on stderr')
  response.end('Hello Node.js Server!')
}

const server = http.createServer(requestHandler)

server.listen(port, (err) => {  
  if (err) {
    return console.log('something bad happened', err)
  }
  console.log(`server is listening on ${port}`)
})
```

The following should appear on stdout:

```
server is listening on 4000
Printing on stdout:  /
```
While I expect this line on stderr:
`Printing on stderr`

But this is what my dashboard looks like:

![nodedash](https://cloud.githubusercontent.com/assets/7949156/19339052/abdf16b0-913e-11e6-9923-5c345318a2c2.png)

**Comment by Aweary** [comment]
@comradealain the `stderr` output shows that you're getting an `EADDRINUSE` error for port 4000, do you have anything else running on that port? Can you try a different port?

**Comment by jasonwilson** [comment]
@comradealain it looks like your app is crashing on startup as @Aweary mentioned. The default port is `9838` and can be changed using the `-p` argument.  Saying that I would verify there isn't a process already running on that port.
