### ISSUE TITLE
don't make us require it in the app

### ISSUE THREAD

**Issue by saelfaer** [FormidableLabs/nodejs-dashboard#16]
I suggest we find a way not to require it in index.js (you do suggest to install it as dev dependency which would mean it is not available in production) 

possible solutions:

* wrap it in a logical test on the environement >>  not ideal, and bloat
* wrap it in a separate dev.index.js which then loads index.js
* ...

**Comment by Volox** [comment]
Also the cli usage can be as simple as:
`nodejs-dashboard app.js`

which under the hood calls `node -r nodejs-dashboard app.js`.

**Comment by pavanmehta91** [comment]
Yes please, Have a global (-g) install available for this module.

**Comment by BLamy** [comment]
I normally go with your second possible suggestion. I place it next to babel-register.

![image](https://cloud.githubusercontent.com/assets/324928/19357982/ea4856d4-9141-11e6-8816-dc25e8ee5f9a.png)

**Comment by jasonwilson** [comment]
Great suggestion @saelfaer  and @Volox-- going to experiment with a couple different options . I like @Volox's idea of using `-r` but we'd need to ensure it's compatible with things like `babel-node`.
