### ISSUE TITLE
Can't work on git-bash

### ISSUE THREAD

**Issue by jrainlau** [FormidableLabs/nodejs-dashboard#21]
Hello! Your work is awesome, but I've found it can not work in git-bash, all the output are mess code. Are there anything I did wrong, or `nodejs-dashboard` doesn't support git-bash yet?
Thanks！

**Comment by jasonwilson** [comment]
@jrainlau can you provide an example of how you're using it?

**Comment by jasonwilson** [comment]
Closing for now. Feel free to reopen if you can provide more details.
