### ISSUE TITLE
Resize graphs on terminal resize

### ISSUE THREAD

**Issue by armed10** [FormidableLabs/nodejs-dashboard#31]
After resizing the terminal, both the outputs and the graphs are resized as well. Only the outputs use this new space, the graphs stay small. 

Tested with 1.0.1 on Ubuntu Trusty LTS (14.04)
![smallgraphs](https://cloud.githubusercontent.com/assets/234881/19430918/8223e9e8-9456-11e6-92ef-c317c868f50a.jpg)

**Comment by jasonwilson** [comment]
Unfortunately [blessed](https://github.com/chjj/blessed) doesn't support resizing of windows when the terminal characteristics change.
