### ISSUE TITLE
Windows 10 ConEmu no Scrollbars 

### ISSUE THREAD

**Issue by cannap** [FormidableLabs/nodejs-dashboard#33]
Hi, i  have no Scrollbars in my ConEmu on  Window 10 and cant scroll any
when i console.log some arrays/object it would be helpfull but i think its a windows problem xD
here a screen: 
https://gyazo.com/beab152e51d0945c14b458e2161c1676

//e but i think its a problem from https://github.com/chjj/blessed

**Comment by jasonwilson** [comment]
Agree that this is likely coming from [blessed](https://github.com/chjj/blessed). Closing for now unless there's a fix.
