### ISSUE TITLE
Running with the Global Binary

### ISSUE THREAD

**Issue by pavanmehta91** [FormidableLabs/nodejs-dashboard#39]
I would ideally not want to touch my package.json/code base at all and run the dashboard via the binary itself.
Is it possible?
I did
nodejs-dashboard npm start It loads the dashboard but does not update the memory and processor usage part.

**Comment by pavanmehta91** [comment]
Here is the screenshot for the same.
http://prnt.sc/cwk1z2

**Comment by jasonwilson** [comment]
@pavanmehta91 did you include the module in your code?

**Comment by jasonwilson** [comment]
@pavanmehta91 haven't heard back from you. Going to close this issue for now but feel free to reopen when you can provide more information.

**Comment by pavanmehta91** [comment]
Thanks for the help Jason. It started to work when I added the module in the code.
I still face the issue of characters not showing properly though. But you can close this issue. I guess that issue is already reported and I'll check that.
