### ISSUE TITLE
Won't work when using foreman

### ISSUE THREAD

**Issue by danielrvt** [FormidableLabs/nodejs-dashboard#46]
This is my Procfile for my LoopbackJS app:

`web: nodejs-dashboard node .`

The problem:
If I run `nf start`, the console just clears and nothing shows up (Not even an error). My app uses a bunch of environment variables and foreman really makes it a breeze to run it.

The expected result:
The dashboard should appear in the terminal running the app. This actually does happen if I run `nodejs-dashboard node .` instead of `nf start`, it just fails with foreman.

**Comment by jasonwilson** [comment]
I'm not familiar with foreman but does it have a mechanism to pass through stderr/stdout? When I try the test app locally it prints ansi escape characters.

Inverting the pattern and creating a foreman npm task for the app:
```
"dev-nf": "nodejs-dashboard -- nf start web"
```

This works as expected but stderr/stdout are consolidated into a single `stdout` stream. Likely related to this issue: https://github.com/strongloop/node-foreman/issues/130

**Comment by jjasonclark** [comment]
Issue solved with reordering of process calls. Closing.
