### ISSUE TITLE
latest version on npm is 0.3.0 but I don't see 0.3.0 in the github repo

### ISSUE THREAD

**Issue by vitosamson** [FormidableLabs/nodejs-dashboard#48]
greenkeeper just notified me that there's a 0.3.0 version available for this project, but I'm not seeing anything about 0.3.0 in this repo.

I also don't see any tags or releases of any kind, or any CHANGELOG to indicate what changed between 0.2.1 and 0.3.0.

can you provide some info on what changed and confirm that this was a legitimate publish to npm?

**Comment by jasonwilson** [comment]
Apologies for the failing to push the latest release. Have remedied that situation and will add a changelog when I get some cycles.
