### ISSUE TITLE
Harmony flags not working

### ISSUE THREAD

**Issue by bbohen** [FormidableLabs/nodejs-dashboard#6]
This tool is awesome but I noticed that when I tried to get it running with an existing project the dashboard would display but nothing would run as the project supports Node v5.X while using harmony flags. 

Works: `"dashboard": "nodejs-dashboard node server.js"`
Doesnt Work: `"dashboard": "nodejs-dashboard node --harmony_destructuring server.js"`

Not sure if the intention is that nodejs-dashboard would only support Node v6 and above (understandable) or if this is a bug/misunderstanding. If it is a bug I would be happy to try and get to the bottom of it when I have some free time later.

**Comment by jasonwilson** [comment]
@bbohen can you provide more details on your environment/node version/etc? Thanks!

**Comment by bbohen** [comment]
Sure thing!

**Node:** v5.6.0 / v5.11.0
**NPM:** v3.8.6
**NPM Script:** `"dashboard": "nodejs-dashboard node --harmony_destructuring server.js"`
**OS:** OSX 10.11.5

When I switch to Node 6 and remove the harmony flags, everything works great. Please let me know if I could provide any other useful info.

**Comment by ryan-roemer** [comment]
Isn't the actual command supposed to be:

```
nodejs-dashboard -- node --harmony_destructuring server.js
```

per the docs and usage string?

The `--` should also preserve all args because they won't get interpolated by commander.

**Comment by bbohen** [comment]
@ryan-roemer Good call! Placing the `--` before `node` fixes the issue for me. As you mentioned in #13 it would be good to beef up the readme examples a bit. Thanks.
