### ISSUE TITLE
Bug: Linux shells cannot have dash-cased environment variable names.

### ISSUE THREAD

**Issue by jjasonclark** [FormidableLabs/nodejs-dashboard#75]
No stats are collected when using `nodemon`. The dashboard app spawns the `nodemon` process which then spawns the actual node app. This is a bit different from using `nodemon` to reload the dashboard app if it terminates. (from issue https://github.com/FormidableLabs/nodejs-dashboard/issues/9)

**Repo steps**

1. Install `nodemon` in the project. `yarn add -D nodemon`
1. Execute test app with `nodemon`: `node bin/nodejs-dashboard.js -- node_modules/.bin/nodemon --exec "node test/app/index.js"`

![no_graph](https://user-images.githubusercontent.com/155233/33406352-440db7d0-d521-11e7-9857-61fc92c0185a.png)

**Comment by jjasonclark** [comment]
I thought this might be related to the child processes not getting included in the parents stats. Although before testing that I discovered that `nodemon` is changing the environment variables of the child process. Check out the differences in the environments for each.

Include the following 2 tasks
```
    "dashboard-env": "node bin/nodejs-dashboard.js -- printenv",
    "nodemon-env": "node bin/nodejs-dashboard.js -- node_modules/.bin/nodemon --exec \"printenv\"",
```

Notice that the non-nodemon version includes the 3 environment values set by the dashboard `nodejs-dashboard_PORT`, `nodejs-dashboard_REFRESH_INTERVAL`, and `nodejs-dashboard_BLOCKED_THRESHOLD` and the nodemon version does not.

**Comment by ryan-roemer** [comment]
Thanks @jjasonclark -- I'll take a look at this. Out of curiosity, which node version are you running?

**Comment by jjasonclark** [comment]
Hehe, good question. Nodemon in Node >= 1.8 adds the shelling out. This test was done with Node 8.9.0

**Comment by ryan-roemer** [comment]
@jjasonclark -- I've created a playground repo for us at https://github.com/FormidableLabs/nodejs-dashboard-75-experiments

Can you pull that down and try things out? I actually see the env vars in both incarnations of your commands there...

Are you on Windows or Mac?

**Comment by jjasonclark** [comment]
I'm on Ubuntu 16.04. And I see the vars using your repo only for the non-nodemon version. The nodemon version does not show the 3 environment values.

**Comment by jjasonclark** [comment]
Created a branch for using a Docker host for consistency. It does repo the issue.

https://github.com/FormidableLabs/nodejs-dashboard-75-experiments/tree/jason_docker

**Comment by ryan-roemer** [comment]
From the docker shell in Alpine:

```
/app # export nodejs-dashboard_PORT=3000
sh: export: nodejs-dashboard_PORT: bad variable name
/app # export nodejs_dashboard_PORT=3000
/app # env | grep nodejs_dashboard_PORT
nodejs_dashboard_PORT=3000
```

Side note: I actually just hacked up `nodemon` itself right before the spawn in `lib/monitor/run.js` with:

```js
    // apk update && apk add vim && vim node_modules/nodemon/lib/monitor/run.js
    process.env["temp-bar_HACK"] = "foo";
    process.env["nodejs-dashboard_PORT"] = process.env["nodejs-dashboard_PORT"];
    console.log("TODO HERE NODEMON", process.env["nodejs-dashboard_PORT"]);
    var merged = utils.merge(options.execOptions.env, process.env);
    console.log("TODO HERE NODEMON MERGED", merged["nodejs-dashboard_PORT"],
      Object.keys(merged).length);
    var stringified = JSON.parse(JSON.stringify(merged));
    console.log("TODO HERE NODEMON STRINGIFED", stringified["nodejs-dashboard_PORT"]);
```

We should most likely switch to underscore case with something like `nodejs_dashboard_*`.

See: http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit.

It looks like other shells (like my Mac) are more permissive.

I'll open a PR.
