### ISSUE TITLE
How does monitoring the event loop works?

### ISSUE THREAD

**Issue by i0natan** [FormidableLabs/nodejs-dashboard#89]
Thanks for the great work. I'm just curious, where/how is the event loop monitoring happens? any reference to a code file/article will be appreciated

**Comment by jasonwilson** [comment]
hey @i0natan, 

The dashboard-agent uses [blocked](https://github.com/tj/node-blocked) to measure eventloop delay. See the agent code and integration  [here](https://github.com/FormidableLabs/nodejs-dashboard/blob/master/lib/dashboard-agent.js#L38-L39).

Feel free to reopen if you have anymore questions!
