### ISSUE TITLE
Using babel-node and nodemon

### ISSUE THREAD

**Issue by kaatt** [FormidableLabs/nodejs-dashboard#9]
`nodejs-dashboard babel-node index.js` works fine.

Dunno how to use it with both nodemon and babel-node.

This is the raw command i used earlier btw: `nodemon index.js --exec babel-node`

**Comment by exogen** [comment]
@kaatt I'm not sure yet whether it makes more sense to run the dashboard within nodemon or nodemon within the dashboard, but this appears to work:

`nodemon --exec "nodejs-dashboard babel-node" src/index.js`

**Comment by imthinhvu** [comment]
I currently have a grunt serve script that runs grunt-nodemon. Is there a possible way to integrate the dashboard with grunt?

**Comment by ryan-roemer** [comment]
@imthinhvu -- Looks like you can pass https://github.com/ChrisWren/grunt-nodemon#exec , so @exogen 's example above may look something like:

```js
nodemon: {
  dev: {
    script: "src/index.js",
    options: {
      exec: "nodejs-dashboard babel-node"
    }
  }
}
```

or

```js
nodemon: {
  dev: {
    script: "src/index.js",
  },
  exec: {
    options: {
      exec: "nodejs-dashboard babel-node"
    }
  }
}
```

(above is totally untested code, but seems to comport with the `grunt-nodemon` docs)

**Comment by avalla** [comment]
@exogen confirm that this works:
```
"command": "nodemon --exec 'nodejs-dashboard babel-node' index",
```

**Comment by wxyyxc1992** [comment]
i run into the same problem:
```
 "watch:server": "./node_modules/.bin/nodemon --exec 'nodejs-dashboard node' './dist/app.bundle.js' --watch './dist'",
```
![f56dae57-4c7d-48d0-92e9-a24b8be6def2](https://cloud.githubusercontent.com/assets/5803001/19350798/c861e7c0-918b-11e6-9d5a-fa476da83ce5.png)

**Comment by aequasi** [comment]
@jasonwilson these mouse events still happen
